#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the funnyString function below.
def funnyString(s):
    l=[]
    l1=[]
    l2=[]
    for i in s:
        num=ord(i)
        l.append(num)
    for i in range(0,len(l)-1):
        num=abs(l[i]-l[i+1])
        l1.append(num)
    l.reverse()
    for i in range(0,len(l)-1):
        num=abs(l[i]-l[i+1])
        l2.append(num)
    if(l1==l2):
        return("Funny")
    else:
        return("Not Funny")


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
