#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the missingNumbers function below.
def missingNumbers(arr, brr):
    m=max(arr+brr)+1
    l=[0 for i in range(m)]
    for i in arr:
        l[i]+=1
    for i in brr:
        l[i]-=1
    l1=[i for i in range(len(l)) if(l[i]!=0)]
    return(l1)
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    m = int(input())

    brr = list(map(int, input().rstrip().split()))

    result = missingNumbers(arr, brr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
