#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Write your code here
    a.sort()
    stack=[]
    top=-1
    res=0
    temp=0
    i=0
    num=0
    while(i<len(a)):
        if(top==-1):
            stack.append(a[i])
            top+=1
            temp=stack[top]
        elif(temp+1==a[i] or temp==a[i]):
            stack.append(a[i])
            top+=1
        else:
            res=max(res,len(stack))
            stack.clear()
            top=-1
            stack.append(a[i])
        i+=1
    if(num==0):
        res=max(res,len(stack))
    return(res)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
